[package]
name = "email-wallet-scripts"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.95"
serde = { version = "1.0.159", features = ["derive"] }
reqwest = { version = "0.11.22", features = ["json", "blocking"] }
tokio = { version = "1.0", features = ["full"] }
ethers = "2.0.10"
dotenv = "0.15.0"

[build-dependencies]
ethers = "2.0.10"
