name: Discord Notification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Send Discord notification for push
      if: github.event_name == 'push'
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d "{
          \"embeds\": [{
            \"title\": \"📝 New Push to Main Branch\",
            \"description\": \"**Repository:** ${{ github.repository }}\n**Branch:** ${{ github.ref_name }}\n**Author:** ${{ github.actor }}\n**Commit:** [\`${{ github.sha }}\`](${{ github.event.head_commit.url }})\n**Message:** ${{ github.event.head_commit.message }}\",
            \"color\": 3447003,
            \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)\",
            \"footer\": {
              \"text\": \"GitHub Actions\"
            }
          }]
        }" \
        $DISCORD_WEBHOOK_URL

    - name: Send Discord notification for merged PR
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d "{
          \"embeds\": [{
            \"title\": \"🎉 Pull Request Merged to Main\",
            \"description\": \"**Repository:** ${{ github.repository }}\n**PR:** [#${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})\n**Author:** ${{ github.event.pull_request.user.login }}\n**Merged by:** ${{ github.actor }}\",
            \"color\": 65280,
            \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)\",
            \"footer\": {
              \"text\": \"GitHub Actions\"
            }
          }]
        }" \
        $DISCORD_WEBHOOK_URL